version: '3.8'

services:

  logparser:
    build: ./logparser
    volumes:
    - ./bike-logs:/app/bike-logs
    - ./json-logs:/app/json-logs

  web:
    build: ./web
    volumes:
    - ./json-logs:/app/json-logs
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  
  mongo:
    image: mongo:4.2.7
    ports:
    - "27017:27017"